targets:
  $default:
    builders:
      offline_geocoder:offline_geocoder:
        options:
          source_file: 'assets/ne_110m_admin_0_countries.geojson'
          output_file: 'lib/offline_geocoder/offline_geocoder.dart'
          extract_properties: {"SOVEREIGNT": "String", "ISO_A2": "String", "LEVEL": "int"}



      
        