name: example
description: Example usage of offline_geocoder package.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  offline_geocoder:
    path: ../
  latlong2: ^0.9.0

dev_dependencies:
  build_runner: ^2.4.6
