builders:
  offline_geocoder:
    import: package:offline_geocoder/offline_geocoder.dart
    builder_factories: ['geoFeatureBuilder']
    build_extensions: 
      .geojson:
        - .dart
    build_to: source
    auto_apply: dependents
    defaults:
      options:
        source_file: ''
        output_file: ''
        extract_properties: {}