name: offline_geocoder
description: A simple package to reverse geocode locations offline.
version: 1.0.0
repository: https://github.com/OPENER-next/offline_geocoder

environment:
  sdk: ^3.1.1

dependencies:
  latlong2: ^0.9.0
  flatbush_dart: ^1.2.2
  build: ^3.0.0
  code_builder: ^4.7.0
  dart_style: ^3.1.1
  recase: ^4.1.0

dev_dependencies:
  lints: ^6.0.0
  build_runner: any
  build_test: ^3.3.0
  test: ^1.24.8