name: offline_geocoder
description: A simple package to reverse geocode locations offline.
version: 1.0.0
repository: https://github.com/OPENER-next/offline_geocoder

environment:
  sdk: ^3.1.1

dependencies:
  latlong2: ^0.8.2
  geojson: ^1.0.0
  build_config: ^1.0.0
  build_runner: ^2.4.6
  code_builder: ^4.7.0
  build: ^2.4.1
  dart_style: ^2.3.3
  recase: ^4.1.0
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

